os: linux
dist: focal
language:
  python
python:
  - "3.8"
before_install:
  - sudo apt-get -y install python3-pip
  - sudo apt-get -y install python-dev graphviz libgraphviz-dev pkg-config
install:  
  - pip install coverage
  - pip install -r requirements.txt
script:
  - coverage run -a treespace.py --online -n 10 -r 30 -g 10
  - cd phylo_generator
  - make
  - cd ..
  - coverage run -a treespace.py --offline -n 10 -r 20 -g 10
  - coverage run -a treespace.py -j -m -f -c -d
after_success:
  - bash <(curl -s https://codecov.io/bash)
