# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: TreespaceREU

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        sudo apt-get -y install python3-pip
        sudo apt-get -y install python-dev graphviz libgraphviz-dev pkg-config
        pip3 install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with coverage
      run: |
        pytest
        coverage run -a treespace.py --test
        coverage run -a treespace.py --online -n 10 -r 30 -g 10
        cd phylo_generator
        make
        cd ..
        coverage run -a treespace.py --offline -n 10 -r 20 -g 10
        coverage run -a treespace.py -j -m -f -c -d
        bash <(curl -s https://codecov.io/bash)
